version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  web:
    build: server-diveschedule/
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - EMAIL_URL=$EMAIL_URL
      - SECRET_KEY=$SECRET_KEY
      - DEBUG=$DEBUG
      - ALLOWED_HOSTS=$ALLOWED_HOSTS
      - CSRF_TRUSTED_ORIGINS=$CSRF_TRUSTED_ORIGINS
      - AWS_MEDIA_BUCKET_NAME=$AWS_MEDIA_BUCKET_NAME
      - AWS_STORAGE_BUCKET_NAME=$AWS_STORAGE_BUCKET_NAME
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
