version: "3.9"

services:
  db:
    image: postgres:alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=diveschedule
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

  api:
    depends_on:
      - db
    build:
      context: server-diveschedule/
      dockerfile: Dockerfile
      args:
        - DB_NAME=$DB_NAME
        - DJANGO_SUPERUSER_PASSWORD=$DJANGO_SUPERUSER_PASSWORD
        - DJANGO_SUPERUSER_EMAIL=$DJANGO_SUPERUSER_EMAIL
        - DB_USER=$DB_USER
        - DB_PASSWORD=$DB_PASSWORD
        - DB_HOST=$DB_HOST
        - DB_PORT=$DB_PORT
        - EMAIL_URL=$EMAIL_URL
        - SECRET_KEY=$SECRET_KEY
        - DEBUG=$DEBUG
        - ALLOWED_HOSTS=$ALLOWED_HOSTS
        - CSRF_TRUSTED_ORIGINS=$CSRF_TRUSTED_ORIGINS
        - CORS_ALLOW_ALL_ORIGINS=$CORS_ALLOW_ALL_ORIGINS
        - AWS_MEDIA_BUCKET_NAME=$AWS_MEDIA_BUCKET_NAME
        - AWS_STORAGE_BUCKET_NAME=$AWS_STORAGE_BUCKET_NAME
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        - REACT_APP_DEV_ENV=$REACT_APP_DEV_ENV
        - REACT_APP_URI=$REACT_APP_URI
        - DB_ENGINE=$DB_ENGINE
    ports:
      - "8000:8000"
    volumes:
      - ./server-diveschedule:/app
    links:
      - db
